version: "3.8"
services:
  db:
    container_name: leads_postgres
    image: ankane/pgvector
    environment:
      POSTGRES_USER: *****
      POSTGRES_PASSWORD: ******
      POSTGRES_DB: leadsdb
    volumes:
      - /data/ldb/pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro  # ← optional but recommended

